export default {
	packages: [],
	package: [],
	categories: [],
	companyType: [],
	educations: [],
	experiences: [],
	levels: [],
	locations: [],
	salaries: [],
	terms: [],
	employee: [],
	paymentGatway: [],
	industries: [],
}