export default {
	user: {},
	packages: [],
	package: [],
	categories: [],
	companyType: [],
	educations: [],
	experiences: [],
	levels: [],
	locations: [],
	company: [],
	salaries: [],
	terms: [],
	employee: [],
	paymentGatway: [],
	industries: [],
	listings: [],
	deposits: [],
	ads: [],
}